port: 3333
socks-port: 23456
redir-port: 23457
allow-lan: true
mode: rule
log-level: error
external-controller: 192.168.50.1:9990
experimental:
  ignore-resolve-fail: true
external-ui: dashboard
external-ui-name: metacubexd
secret: "clash"
profile:
  store-selected: true
  store-fake-ip: true
ipv6: true

routing-mark: 255

tproxy: true
tproxy-port: 23458
