name: Purge jsDelivr

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch: # 手动触发workflow的选项

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Get list of files
      run: |
        find . -type f ! -path "./.github/*" > files.txt
        cat files.txt

    - name: Purge jsDelivr cache
      run: |
        while read file; do
          file_path=${file#./} # Remove the leading './'
          curl -X PURGE "https://purge.jsdelivr.net/gh/${{ github.repository }}@master/$file_path"
        done < files.txt
